server:
  port: 8003

spring:
  application:
    name: product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个

eureka:
 client:
  registerWithEureka: true # 服务注册开关
  fetchRegistry: true # 服务发现开关
  serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
   defaultZone: http://localhost:6001/eureka